### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sshaw** [globalizejs/globalize#851]
Versions: 

```
/tmp/globalize-test >node -v
v9.5.0
/tmp/globalize-test >npm ls
/private/tmp/globalize-test
└─┬ globalize@1.4.0
  └── cldrjs@0.5.0
```

Code: 

```js
const Globalize = require("globalize");
Globalize.loadMessages({
  pt: {
    greetings: {
      hello: "Olá",
      bye: "Tchau"
    }
  }
});

Globalize( "pt" ).formatMessage( "greetings/hello" );
```

I get the following: 

```
/tmp/globalize-test >node i18n-test.js
/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:185
			language = maxLanguageId[ 0 ],
			                        ^

TypeError: Cannot read property '0' of undefined
    at coreRemoveLikelySubtags (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:185:28)
    at /private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:300:17
    at Array.forEach (<anonymous>)
    at arrayForEach (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:272:17)
    at bundleLookup (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:296:4)
    at Cldr.init (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:620:12)
    at Cldr.init (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr/event.js:554:13)
    at Cldr.init (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr/supplemental.js:92:13)
    at new Cldr (/private/tmp/globalize-test/node_modules/cldrjs/dist/cldr.js:545:8)
    at alwaysCldr (/private/tmp/globalize-test/node_modules/globalize/dist/globalize.js:319:55)
```

**Comment by sshaw** [comment]
Problem is lack of CLDR data (though this is still a bug, IMHO). Once one calls:

```
Globalize.load( require( "cldr-data" ).entireSupplemental() );
```
(or similar) this error is not raised.

**Comment by theodesp** [comment]
You only need to load the `cldr/supplemental/likelySubtags` to fix that

**Comment by rxaviers** [comment]
> You only need to load the cldr/supplemental/likelySubtags to fix that

:+1: 

The action item is to improve https://github.com/rxaviers/cldrjs error handling.

**Comment by rxaviers** [comment]
I'm closing this issue. PR in cldrjs is welcome. Thanks
