### ISSUE TITLE
unitFormatter throw exception for locale "pl" with cldr-data 35

### ISSUE THREAD

**Issue by LilyLi2019** [globalizejs/globalize#934]
var formatter = Globalize("pl-PL").unitFormatter( 'digital-petabyte', { form: 'long' } );
console.log(formatter( 2 ));

It throws exceptions:
PS C:\LilyLi\VMC\devCode\testCode> node .\test.ts
C:\LilyLi\VMC\devCode\testCode\node_modules\globalize\dist\globalize.js:73
        message = message.replace( /{[0-9a-zA-Z-_. ]+}/g, function( name ) {
                          ^

TypeError: Cannot read property 'replace' of undefined
    at formatMessage (C:\LilyLi\VMC\devCode\testCode\node_modules\globalize\dist\globalize.js:73:20)
    at unitFormat (C:\LilyLi\VMC\devCode\testCode\node_modules\globalize\dist\globalize\unit.js:89:9)
    at unitFormatter (C:\LilyLi\VMC\devCode\testCode\node_modules\globalize\dist\globalize\unit.js:100:10)
    at Object.<anonymous> (C:\LilyLi\VMC\devCode\testCode\test.ts:143:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

Please note:
It works good with cldr-data version 34.
But it failed with above exception with cldr-data version 35, 36.

**Comment by rxaviers** [comment]
Thank you for filing the issue. Please, is it a dup of #932? I see the new data has additional forms ([link](https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-units-full/main/pl/units.json#L835-L850)) compared to v34 ([link](https://github.com/unicode-cldr/cldr-units-full/blob/cldr-34/main/pl/units.json#L203-L209)). We need to figure out what's missing from the data that the current code considers present but is `undefined`. We may also want to check updated specs https://www.unicode.org/reports/tr35/tr35-numbers.html so that code updates match specs.

I am open for PR fixing it.

**Comment by rxaviers** [comment]
No problem and thank you
